site_name: DevOps Lectures
theme:
  name: material
  language: en
nav:
  - Home: content/index.md
  - Lecture 1: content/01_LECTURE.md
  - Lecture 2: content/02_LECTURE.md
  - Lecture 3: content/03_LECTURE.md
  - Lecture 4: content/04_LECTURE.md
  - Lecture 5: content/05_LECTURE.md
