site_name: DevOps Lectures
docs_dir: content
theme:
  name: material
  language: en
nav:
  - Home: index.md
  - Lecture 1: 01_LECTURE.md
  - Lecture 2: 02_LECTURE.md
  - Lecture 3: 03_LECTURE.md
  - Lecture 4: 04_LECTURE.md
  - Lecture 5: 05_LECTURE.md