name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      # 1. Repository vom GitHub Server auf den Build-Server ziehen
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker Compose Build & Run im Arbeitsverzeichnis
      - name: Build and run Docker Compose
        run: |
          cd $GITHUB_WORKSPACE
          docker compose up --build -d

      # 3. Optional: weitere Steps
      - name: Post build info
        run: |
          echo "Build complete. Running containers:"
          docker ps -a
