name: DevOps Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Fix permissions before checkout
        run: |
          echo "Fixing leftover root-owned files..."
          docker run --rm -v "${PWD}":/project bash:latest bash -c "chown -R $(id -u):$(id -g) /project || true"

      # --- Checkout & Setup ---
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # --- Build, Test & Coverage ---
      - name: Build with Gradle (incl. JaCoCo)
        run: ./gradlew clean test jacocoTestReport bootJar

      - name: Prepare coverage report for SonarQube
        run: |
          mkdir -p src/coverage
          cp build/reports/jacoco/test/jacocoTestReport.xml src/coverage/

      # --- SonarQube Analysis ---
      - name: Run SonarQube analysis
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="http://10.0.40.193:9000" \
            -e SONAR_TOKEN="sqp_dcf970c3a33631566aabe8542a6bd133a3d8284d" \
            -v "$(pwd)/src:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=Team9 \
            -Dsonar.sources=. \
            -Dsonar.java.binaries=. \
            -Dsonar.coverage.jacoco.xmlReportPaths=coverage/jacocoTestReport.xml

      # --- Build & Deploy App ---
      - name: Build Docker image (tag with commit SHA, plus latest)
        run: |
          IMAGE_TAG="devops-app-team9:${{ github.sha }}"
          docker build -t "$IMAGE_TAG" .
          docker tag "$IMAGE_TAG" devops-app-team9:latest

      - name: Stop and remove old container (ignore errors)
        run: |
          docker stop devops-app-team9 || true
          docker rm devops-app-team9 || true

      - name: Run container
        run: |
          docker run -d --name devops-app-team9 \
            --restart unless-stopped \
            -p 8080:8080 devops-app-team9:latest

      # --- Integration Test ---
      - name: Wait & Run integration tests
        run: |
          chmod +x ci/integration-test.sh
          ./ci/integration-test.sh

      # --- Push App image to Registry ---
      - name: Tag and push App image to registry
        run: |
          REG="10.0.40.193:5000"
          IMAGE_TAG="devops-app-team9:${{ github.sha }}"
          REG_IMAGE="$REG/devops-app-team9:${{ github.sha }}"
          docker tag "$IMAGE_TAG" "$REG_IMAGE"
          docker push "$REG_IMAGE"
          docker tag devops-app-team9:latest "$REG/devops-app-team9:latest"
          docker push "$REG/devops-app-team9:latest"

      # --- Documentation Build & Container ---
      - name: Set file and folder permissions to local user
        run: |
          echo "Setting file and folder permissions in case something with user and group root was created in a previous run."
          echo "Using user and group $(id -u):$(id -g) for the whole folder."
          docker run --rm -v "${PWD}":/project bash:latest chown --recursive $(id -u):$(id -g) /project

      - name: Build the documentation
        run: |
          docker run --rm \
            -u "$(id -u):$(id -g)" \
            -v "${PWD}/docs:/docs" \
            -w /docs \
            squidfunk/mkdocs-material build -d build/site

      - name: Generate PDF documentation with Pandoc
        run: |
          docker run --rm \
            -v "${PWD}/docs:/data" \
            -w /data/content \
            pandoc/latex \
            -s index.md 01_LECTURE.md 02_LECTURE.md 03_LECTURE.md 04_LECTURE.md 05_LECTURE.md 06_LECTURE.md 07_LECTURE.md 08_LECTURE.md \
            -o ../build/site/documentation.pdf \
            --metadata title="DevOps Lectures Documentation" \
            --toc

      - name: Create the documentation container
        run: |
          docker image rm my-documentation || true
          docker build -f Dockerfile.nginx -t my-documentation .
          docker image ls --all
          

      - name: Tag and push Documentation image to registry
        run: |
          REG="10.0.40.193:5000"
          DOC_IMAGE_LOCAL="my-documentation"
          DOC_IMAGE_REMOTE="$REG/team9-docs:latest"
          docker tag "$DOC_IMAGE_LOCAL" "$DOC_IMAGE_REMOTE"
          docker push "$DOC_IMAGE_REMOTE"
          

      - name: Run the documentation container
        run: |
          docker container stop mydoc || true
          docker container rm mydoc || true
          docker run --name mydoc -d --restart always -p 8081:80 my-documentation

      - name: Test the documentation container
        run: |
          chmod +x ci/doc-integration-test.sh
          ./ci/doc-integration-test.sh
          
      - name: SSH connection test (print date)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          ssh-keyscan -H 10.0.40.194 > known_hosts

          ssh -i key.pem -o UserKnownHostsFile=known_hosts svcgithub@10.0.40.194 "date"


      - name: Deploy containers to production (Team 9)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh-keyscan -H 10.0.40.194 > known_hosts

          ssh -i key.pem -o UserKnownHostsFile=known_hosts svcgithub@10.0.40.194 '
            docker stop devops-app-team9 || true &&
            docker rm devops-app-team9 || true &&
            docker stop mydoc || true &&
            docker rm mydoc || true
          '

          ssh -i key.pem -o UserKnownHostsFile=known_hosts svcgithub@10.0.40.194 '
            docker image prune -f
          '

          ssh -i key.pem -o UserKnownHostsFile=known_hosts svcgithub@10.0.40.194 '
            REG="10.0.40.193:5000"
            docker pull $REG/devops-app-team9:latest
            docker pull $REG/team9-docs:latest
          '

          ssh -i key.pem -o UserKnownHostsFile=known_hosts svcgithub@10.0.40.194 '
            REG="10.0.40.193:5000"
            docker run -d --restart always --name devops-app-team9 -p 1891:8080 $REG/devops-app-team9:latest &&
            docker run -d --restart always --name mydoc -p 1892:80 $REG/team9-docs:latest
          '
